FROM nextcloud:22.0.0
COPY policy.php /usr/src/nextcloud/lib/public/AppFramework/Http/ContentSecurityPolicy.php
COPY policy.php /var/www/html/lib/public/AppFramework/Http/ContentSecurityPolicy.php
COPY publicpage.js /var/www/html/core/js/public/publicpage.js
