server:
  port:
    8081

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/users/**
      - id: course-service
        uri: lb://course-service
        predicates:
          - Path=/courses/**

  application:
    name:
      api-gateway
  discovery:
    locator:
      enabled: true
      lowerCaseServiceId: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
            http://localhost:8181/auth/realms/e-learning

eureka:
  client:
    service-url:
      defaultZone:
        http://eureka:password@localhost:8888/eureka