server:
  port:
    8081

spring:
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/users/**

      - id: course-service
        uri: lb://course-service
        predicates:
          - Path=/courses/**
        filters:
          - Logging=
          - TokenRelay=
          - RemoveRequestHeader=Cookie
      - id: media-service
        uri: lb://media-service
        predicates:
          - Path=/media/**
      - id: user-courses-service
        uri: lb://user-courses-service
        predicates:
          - Path=/user-courses/**
     
      - id: payment-service
        uri: lb://payment-service
        predicates:
          - Path=/payment/**
        filters:
          - Logging=
          - TokenRelay=
          - RemoveRequestHeader=Cookie

      - id: certification-service
        uri: lb://certification-service
        predicates:
          - Path=/certifications/**




  application:
    name:
      api-gateway
  discovery:
    locator:
      enabled: true
      lowerCaseServiceId: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
            http://localhost:8181/auth/realms/e-learning

eureka:
  client:
    service-url:
      defaultZone:
        http://eureka:password@localhost:8888/eureka
