server:
  port:
    8081

spring:
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/users/**
      - id: course-service
        uri: lb://course-service
        predicates:
          - Path=/courses/**
      - id: media-service
        uri: lb://media-service
        predicates:
          - Path=/media/**

  application:
    name:
      api-gateway
  discovery:
    locator:
      enabled: true
      lowerCaseServiceId: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:
            http://localhost:8181/auth/realms/e-learning

eureka:
  client:
    service-url:
      defaultZone:
        http://eureka:password@localhost:8888/eureka
